version: "3"
services:
  postgres:
    image: postgres:15.3
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  client:
    build: ./client
    ports:
      - 3000:3000
    environment:
      - REACT_APP_SERVER_URL=http://server:5000
    depends_on:
      - server

  server:
    build: ./server
    environment:
      - LOGIN_USERNAME=${LOGIN_USERNAME}
      - LOGIN_PASSWORD=${LOGIN_PASSWORD}
    depends_on:
      - postgres

volumes:
  db-data:
